# Model Specification
model:
  type: DeepLabv3p
  backbone: Xception

optimizer:
  type: adamw
  args:
    weight_decay: 1.e-3
  schedule: warmup_cosine_decay_schedule
  schedule_args:
    init_value: 1.e-7
    peak_value: 1.e-3
    warmup_steps: 10_000
    end_value:  4.e-5
    decay_steps: 240_000

train:
  steps: 250_000
  loss_supervised: bce
  loss_semisupervised: noop
  semisupervised_weight: 1

validation:
  frequency: 1_000
  image_frequency: 10_000

# Data args
datasets:
  # Dummy unlabelled dataset, not evaluated anyways
  train_unlabelled:
    batch_size: 1
    tile_size: 256
    threads: 4
    sampling_mode: random
    root: '/data/RTS/s2_4w/'
    datasets: ['Sentinel2']
    scenes:
      - Horton/*
      # - 11XMB_2018
      # - 40XDG_2018
      # - 49XEE_2018
      # - 53WMR_2019
  val:
    batch_size: 16
    tile_size: 256
    threads: 4
    sampling_mode: deterministic
    root: '/data/RTS/s2_4w'
    datasets: ['Sentinel2', 'Mask']
    scenes:
      - Herschel/*
  train_labelled:
    batch_size: 16
    tile_size: 256
    threads: 4
    sampling_mode: targets_only_singletime
    root: '/data/RTS/s2_4w'
    datasets: ['Sentinel2', 'Mask']
    scenes:
      - Banks Island/*
      - Chukotka/*
      - Gydan/*
      - Horton/*
      - Kolguev/*
      - Lena/*
      - Lena Delta/*
      - Novaya Zemlya/*
      - Peel Plateau/*
      - Taimyr/*
      - Tuktoyaktuk/*
