# Model Specification
model:
  type: UNet
  width: 16

optimizer:
  type: adamw
  args:
    weight_decay: 1.e-3
  schedule: warmup_cosine_decay_schedule
  schedule_args:
    init_value: 1.e-7
    peak_value: 1.e-3
    warmup_steps: 10_000
    end_value:  4.e-5
    decay_steps: 240_000

loss_functions:
  train: bce

train:
  steps: 200_000
  temperature: 0.5
  unlabelled_weight: 0.1

validation:
  frequency: 1_000
  image_frequency: 10_000

# Data args
datasets:
  val_Herschel:
    batch_size: 16
    shuffle: false
    split: val_Herschel
  val_Chukotka:
    batch_size: 16
    shuffle: false
    split: val_Chukotka
  train:
    batch_size: 16
    shuffle: true
    augment: true
    split: train
