# Model Specification
model:
  type: UNet
  width: 32

optimizer:
  type: adamw
  args:
    weight_decay: 1.e-3
  schedule: warmup_cosine_decay_schedule
  schedule_args:
    init_value: 1.e-7
    peak_value: 1.e-3
    warmup_steps: 10_000
    end_value:  2.e-4
    decay_steps: 240_000

loss_functions:
  train: bce

train:
  group: sinkhorn_knopp
  steps: 300_000
  temperature: 0.5
  unlabelled_bs: 16
  teacher_ema: 0.996
  center_ema: 0.996
  n_pseudoclasses: 48
  teacher_norm: center
  koleo_weight: 0.1

validation:
  frequency: 1_000
  image_steps: [10_000, 100_000, 200_000, 300_000]

# Data args
datasets:
  val_Herschel:
    batch_size: 16
    shuffle: false
    split: val_Herschel
  val_Lena:
    batch_size: 16
    shuffle: false
    split: val_Lena
